# Generated by Django 2.1.5 on 2019-01-20 04:02

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20190119_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='date',
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
    ]
