# Generated by Django 2.1.5 on 2019-01-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_workday_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='work_day',
        ),
        migrations.AddField(
            model_name='workday',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='expenses.Project'),
        ),
    ]
