# Generated by Django 2.1.5 on 2019-01-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20190119_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='project',
            field=models.ManyToManyField(blank=True, to='expenses.Project'),
        ),
    ]
