# Generated by Django 2.1.5 on 2019-01-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20190119_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='employee',
            field=models.ManyToManyField(blank=True, to='expenses.Employee'),
        ),
    ]
