# Generated by Django 2.1.5 on 2019-01-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_workday_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
