# Generated by Django 2.1.5 on 2019-01-20 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_employee_base_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='workday',
            name='employee_salary_adjustment',
            field=models.ManyToManyField(blank=True, to='expenses.EmployeeSalaryAdjustment'),
        ),
    ]
