# Generated by Django 2.1.5 on 2019-01-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_auto_20190120_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
