# Generated by Django 2.1.5 on 2019-01-20 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_workday_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='project',
        ),
        migrations.AddField(
            model_name='workday',
            name='project',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.Project'),
            preserve_default=False,
        ),
    ]
