# Generated by Django 2.1.5 on 2019-01-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_auto_20190120_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
