# Generated by Django 2.1.5 on 2019-01-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='expenses.Image'),
        ),
    ]
