# Generated by Django 2.1.5 on 2019-01-22 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0020_client_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workday',
            old_name='images',
            new_name='image',
        ),
    ]
