# Generated by Django 2.1.5 on 2019-01-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('expenses', '0021_auto_20190121_1905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='workday',
            old_name='image',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='workday',
            name='slug',
            field=models.SlugField(),
        ),
    ]
