# Generated by Django 2.1.5 on 2019-02-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0022_auto_20190126_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_choices', models.CharField(choices=[('01', 'Plans/Pemrmits'), ('02', 'Demolition'), ('03', 'Foundation')], max_length=2)),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.WorkDay')),
            ],
        ),
    ]
