# Generated by Django 2.1.5 on 2019-02-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0023_constructiondivision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructiondivision',
            name='division_choices',
        ),
        migrations.AddField(
            model_name='constructiondivision',
            name='division_choice',
            field=models.CharField(choices=[('01', 'Plans/Permits'), ('02', 'Demolition'), ('03', 'Foundation')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
