# Generated by Django 2.1.5 on 2019-02-03 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0024_auto_20190203_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='workday',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='workday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.WorkDay'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constructiondivision',
            name='division_choice',
            field=models.CharField(choices=[('01', 'Plans/Permits'), ('02', 'Demolition'), ('03', 'Foundation'), ('04', 'Roof/Gutters'), ('05', 'Exterior/Siding'), ('06', 'Windows'), ('07', 'Garage/Driveway'), ('08', 'Framing'), ('09', 'Finish Carpentry'), ('10', 'Sheetrock/Insulation'), ('11', 'Interior Paint'), ('12', 'Flooring'), ('13', 'Kitchen'), ('14', 'Bathrooms'), ('15', 'Plumbing Work'), ('16', 'Electrical Work'), ('17', 'HVAC Work'), ('18', 'Appliances'), ('19', 'Yard/Landscaping'), ('20', 'Basement Finishes')], max_length=2),
        ),
        migrations.AddField(
            model_name='expense',
            name='workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.WorkDay'),
        ),
    ]
