# Generated by Django 2.1.5 on 2019-02-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0025_auto_20190203_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='file',
            field=models.FileField(default=0, upload_to='attachments'),
            preserve_default=False,
        ),
    ]
