# Generated by Django 2.1.5 on 2019-02-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0028_auto_20190204_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructiondivision',
            name='workday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expenses.WorkDay'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='file',
            field=models.FileField(blank=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='file',
            name='workday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.WorkDay'),
        ),
    ]
