# Generated by Django 2.1.5 on 2019-02-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0029_auto_20190217_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructiondivision',
            name='workday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='construction_division', to='expenses.WorkDay'),
        ),
    ]
