# Generated by Django 2.1.5 on 2019-02-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0030_auto_20190217_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubContractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ein_number', models.CharField(blank=True, max_length=200, null=True)),
                ('license_number', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubContractorProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Project')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.SubContractor')),
            ],
        ),
        migrations.AlterField(
            model_name='constructiondivision',
            name='workday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='construction_division', to='expenses.WorkDay'),
        ),
        migrations.AddField(
            model_name='constructiondivision',
            name='subcontractor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='construction_division', to='expenses.SubContractor'),
        ),
        migrations.AddField(
            model_name='workday',
            name='subcontractor_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.SubContractorProject'),
        ),
    ]
