# Generated by Django 2.1.5 on 2019-02-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0031_auto_20190217_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractorproject',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
