# Generated by Django 2.1.5 on 2019-02-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0032_subcontractorproject_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontractorproject',
            name='slug',
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
