# Generated by Django 2.1.5 on 2019-02-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0033_auto_20190217_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractor',
            name='main_contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
