# Generated by Django 2.1.5 on 2019-02-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0035_auto_20190217_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractorproject',
            name='day',
            field=models.ManyToManyField(blank=True, to='expenses.Day'),
        ),
    ]
