# Generated by Django 2.1.5 on 2019-02-17 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0037_auto_20190217_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.Day'),
        ),
    ]
