# Generated by Django 2.1.5 on 2019-02-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0039_file_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='subcontractor_project',
        ),
    ]
