# Generated by Django 2.1.5 on 2019-02-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0040_remove_workday_subcontractor_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='division_choice',
            field=models.CharField(blank=True, choices=[('01', 'Plans/Permits'), ('02', 'Demolition'), ('03', 'Foundation'), ('04', 'Roof/Gutters'), ('05', 'Exterior/Siding'), ('06', 'Windows'), ('07', 'Garage/Driveway'), ('08', 'Framing'), ('09', 'Finish Carpentry'), ('10', 'Sheetrock/Insulation'), ('11', 'Interior Paint'), ('12', 'Flooring'), ('13', 'Kitchen'), ('14', 'Bathrooms'), ('15', 'Plumbing Work'), ('16', 'Electrical Work'), ('17', 'HVAC Work'), ('18', 'Appliances'), ('19', 'Yard/Landscaping'), ('20', 'Basement Finishes')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subcontractorproject',
            name='division_choice',
            field=models.CharField(blank=True, choices=[('01', 'Plans/Permits'), ('02', 'Demolition'), ('03', 'Foundation'), ('04', 'Roof/Gutters'), ('05', 'Exterior/Siding'), ('06', 'Windows'), ('07', 'Garage/Driveway'), ('08', 'Framing'), ('09', 'Finish Carpentry'), ('10', 'Sheetrock/Insulation'), ('11', 'Interior Paint'), ('12', 'Flooring'), ('13', 'Kitchen'), ('14', 'Bathrooms'), ('15', 'Plumbing Work'), ('16', 'Electrical Work'), ('17', 'HVAC Work'), ('18', 'Appliances'), ('19', 'Yard/Landscaping'), ('20', 'Basement Finishes')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='division_choice',
            field=models.CharField(blank=True, choices=[('01', 'Plans/Permits'), ('02', 'Demolition'), ('03', 'Foundation'), ('04', 'Roof/Gutters'), ('05', 'Exterior/Siding'), ('06', 'Windows'), ('07', 'Garage/Driveway'), ('08', 'Framing'), ('09', 'Finish Carpentry'), ('10', 'Sheetrock/Insulation'), ('11', 'Interior Paint'), ('12', 'Flooring'), ('13', 'Kitchen'), ('14', 'Bathrooms'), ('15', 'Plumbing Work'), ('16', 'Electrical Work'), ('17', 'HVAC Work'), ('18', 'Appliances'), ('19', 'Yard/Landscaping'), ('20', 'Basement Finishes')], max_length=2, null=True),
        ),
    ]
