# Generated by Django 2.1.5 on 2019-02-17 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0041_auto_20190217_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.Day'),
        ),
        migrations.AlterField(
            model_name='file',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.Day'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.Day'),
        ),
    ]
