# Generated by Django 2.1.5 on 2019-02-18 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0042_auto_20190217_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='workday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.WorkDay'),
        ),
    ]
