# Generated by Django 2.1.5 on 2019-02-20 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0043_auto_20190218_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructiondivision',
            name='subcontractor',
        ),
        migrations.RemoveField(
            model_name='constructiondivision',
            name='workday',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='construction_division',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='workday',
        ),
        migrations.RemoveField(
            model_name='file',
            name='workday',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='slug',
        ),
        migrations.DeleteModel(
            name='ConstructionDivision',
        ),
    ]
