# Generated by Django 2.1.5 on 2019-02-20 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0044_auto_20190219_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='division_choice',
            field=models.CharField(choices=[('01', 'Plans/Permits'), ('02', 'Demolition'), ('03', 'Foundation'), ('04', 'Roof/Gutters'), ('05', 'Exterior/Siding'), ('06', 'Windows'), ('07', 'Garage/Driveway'), ('08', 'Framing'), ('09', 'Finish Carpentry'), ('10', 'Sheetrock/Insulation'), ('11', 'Interior Paint'), ('12', 'Flooring'), ('13', 'Kitchen'), ('14', 'Bathrooms'), ('15', 'Plumbing Work'), ('16', 'Electrical Work'), ('17', 'HVAC Work'), ('18', 'Appliances'), ('19', 'Yard/Landscaping'), ('20', 'Basement Finishes')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workday',
            name='division_choice',
            field=models.CharField(choices=[('01', 'Plans/Permits'), ('02', 'Demolition'), ('03', 'Foundation'), ('04', 'Roof/Gutters'), ('05', 'Exterior/Siding'), ('06', 'Windows'), ('07', 'Garage/Driveway'), ('08', 'Framing'), ('09', 'Finish Carpentry'), ('10', 'Sheetrock/Insulation'), ('11', 'Interior Paint'), ('12', 'Flooring'), ('13', 'Kitchen'), ('14', 'Bathrooms'), ('15', 'Plumbing Work'), ('16', 'Electrical Work'), ('17', 'HVAC Work'), ('18', 'Appliances'), ('19', 'Yard/Landscaping'), ('20', 'Basement Finishes')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
