# Generated by Django 2.1.5 on 2019-03-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0045_auto_20190219_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Day')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Project')),
            ],
        ),
        migrations.CreateModel(
            name='SubContractorPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Day')),
                ('subcontractor_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.SubContractorProject')),
            ],
        ),
    ]
