# Generated by Django 2.1.5 on 2019-05-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0046_income_subcontractorpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pay_period',
            field=models.CharField(blank=True, choices=[('01', 'Weekly'), ('02', 'Bi-Weekly'), ('03', 'Semi-Monthly'), ('04', 'Monthly')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salaried',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
