# Generated by Django 2.1.5 on 2019-05-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0047_auto_20190525_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
