# Generated by Django 2.1.5 on 2019-05-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0048_auto_20190525_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='foreman',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
