# Generated by Django 2.1.5 on 2019-05-26 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0049_employee_foreman'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCalculatedPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='workday',
            name='employee_calculated_salary',
            field=models.ManyToManyField(blank=True, to='expenses.EmployeeCalculatedPay'),
        ),
    ]
