# Generated by Django 2.1.5 on 2019-05-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0050_auto_20190526_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_pay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
