# Generated by Django 2.1.5 on 2019-05-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0052_auto_20190526_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='daily_pay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pay_period',
            field=models.CharField(blank=True, choices=[('01', 'Weekly'), ('02', 'Bi-Weekly'), ('03', 'Semi-Monthly'), ('04', 'Monthly'), ('05', 'Daily')], max_length=2, null=True),
        ),
    ]
