# Generated by Django 2.1.5 on 2019-05-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0053_auto_20190526_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='daily_pay',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
