# Generated by Django 2.1.5 on 2019-05-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0054_auto_20190526_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='employee_calculated_salary',
            field=models.ManyToManyField(blank=True, editable=False, to='expenses.EmployeeCalculatedPay'),
        ),
    ]
