# Generated by Django 2.2.1 on 2019-06-02 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0055_auto_20190526_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='subcontractor_project',
        ),
        migrations.CreateModel(
            name='SubContractorProjectDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('division_choice', models.CharField(choices=[('01', 'Plans/Permits'), ('02', 'Demolition'), ('03', 'Foundation'), ('04', 'Roof/Gutters'), ('05', 'Exterior/Siding'), ('06', 'Windows'), ('07', 'Garage/Driveway'), ('08', 'Framing'), ('09', 'Finish Carpentry'), ('10', 'Sheetrock/Insulation'), ('11', 'Interior Paint'), ('12', 'Flooring'), ('13', 'Kitchen'), ('14', 'Bathrooms'), ('15', 'Plumbing Work'), ('16', 'Electrical Work'), ('17', 'HVAC Work'), ('18', 'Appliances'), ('19', 'Yard/Landscaping'), ('20', 'Basement Finishes')], max_length=2)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.Day')),
                ('subcontractor_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.SubContractorProject')),
            ],
        ),
    ]
